---
layout: post
title: "Measures of urbanization and the influence of environmental factors on avian reproductive success"
date: 2016-09-06
---


<p>Last week, a friend sent me a link to a news story about an advance access article in <i>Behavioral Ecology</i> about the impacts of urbanization on avian reproductive success that hadn't come across my radar yet. Amusingly, he did not realize that the article was on a topic closely related to my research, and had simply sent it to me because he saw a news story on Reddit that had the word "bird" in the title. As other birders know, this is not a rare occurrence, though it happens less frequently than people showing you a picture of a fairly common backyard bird and asking what it is. The paper is adding to the methods section of my dissertation proposal though, so I'll take it and give him full credit for informing me about the study. </p>

<h2>Thoughts on "Multidimensional environmental predictors of variation in avian forest and city life histories"</h2>

<p>Many studies have documented how populations respond to changing environmental conditions, such as altered reproductive timing due to increased global temperatures or low food availability lowering clutch size. Urbanization presents a unique opportunity to study these alterations and microevolutionary responses to environmental changes because it occurs at such a rapid rate and is an extreme form of land-use changes. 
</p><p>
Past studies of the impact of urbanization on populations have typically used an experimental design in which an urban population is compared to a rural population. These studies use a dichotomous approach and overlook the gradient in between urban and rural, which is not a clean distinction (for a good discussion of this lack of distinction and historical transformation of rural to urban, read the "Prologue: Cloud Over Chicago" in <i>Nature's Metropolis</i> by Cronon). This dichotomy also fails to account for the various environmental factors that create a measurement of urbanization, namely light and noise pollution, temperature (the "urban heat island"), and humidity. The present studied adopted all three approaches. 
</p><p>
The authors assumed that alterations and expression of life history traits would be best studied under the approach of looking at the compound effects of light, noise, temperature, and humidity. What they found was that their dichotomous model contrasting urban and rural (forested) fit the data best. Because this result was surprising, they checked to see if it was an <i>a posteriori</i> effect, but it was not. Before delving in to why I disagree with the authors conclusion that their results suggest that differences in urban and rural areas are unrelated to specific environmental factors and advocating for a more holistic measurement of urbanization, I want to first summarize their core findings.
</p><p>
The primary differences that the study found between the urban and rural birds was that urban birds had an earlier lay date and lower body mass in nestlings. The authors suggest that the earlier lay date may be a reaction to food availability or predictability of urban areas. Although my initial reaction was to assume that earlier laying times are likely attributable to higher temperatures (see Gienapp et al., 2010, for a study on temperature and day length effects on lay dates in Finnish great tits), the authors the "differences persisted after controlling for temperature, humidity, light, and noise." This conflicts with prior research, including studies cited by the authors, about the impact of temperature on lay date. To me, this suggests that there are additional factors not measured in the study that are impacting lay dates and lower body mass, such as food availability or light. Yes, I know, the authors say they controlled for light. However, they measured light only at night to account for ambient light pollution. This method does accurately track ambient light pollution, but it fails to account for increased exposure to sunlight due to reduced vegetation cover in urban areas compared to forests. This additional exposure, if quantified, could potentially explain the earlier lay dates. 
</p><p>
After finding that the best fit model was the dichotomous "citiness" variable contrasting urban and rural areas, the authors state that their "findings imply that one should be very cautious in attributing differences between forest and city populations to specific environmental factors." They later conclude that "our findings question the common interpretation that differences between forest and city areas relate to specific environmental axes that covary with urbanization." While these statements may be true for the factors the authors used to measure urbanization (i.e. light, noise, temperature, and humidity), this does not allow for the possibility that the measure of urbanization used in the study is not capturing all aspects of urbanization. Other factors that the authors may want to consider when measuring urbanization include degree of habitat fragmentation, patch size, amount of impervious surfaces in the surrounding matrix, human population density, presence of predators, and food availability. Of these other potential explanatory variables, the degree of habitat fragmentation seems likely to account for variance not explained by the model. A more holistic approach to measuring urbanization may shed more light on which specific environmental differences between urban and rural areas are impacting bird populations. 
</p><p>
Lastly, I would advocate for a more thorough consideration of the gradient of urbanization. Although the authors included this as a possibility, the study sites (see the Supplementary Material) are distinctly grouped into a forested area and a highly urban area, with no study sites in a suburban or moderately densely populated area. This experimental design doesn't properly distribute sites in order to have a true gradient measure, which could bias the data in favor of the dichotomous model. Future studies should seek to stratify sample sites to capture greater variation in degree of urbanization.
</p>

<h2>Further Reading</h2>

<p>Cronon, W. (1991). <i>Nature's Metropolis</i>. New York, NY: Norton.
</p><p>
Gienapp, P., Valsanen, R.A., & Brommer, J.E. (2010). Latitudinal variation in breeding time reaction norms in a passerine bird. <i>Journal of Animal Ecology</i>, 79(4): 836-842.
</p><p>
Sprau, P., Mouchet, A., & Dingemanse, N.J. (2016). Multidimensional environmental predictors of variation in avian forest and city life histories. <i>Behavioral Ecology</i>, xx(xx): xx-xx.
</p>

